// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: data/pb/seed.proto

package seedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PointOfInterestType int32

const (
	PointOfInterestType_Headquarters               PointOfInterestType = 0
	PointOfInterestType_WarpConduitSender          PointOfInterestType = 1
	PointOfInterestType_WarpConduitReceiver        PointOfInterestType = 2
	PointOfInterestType_WarpPortal                 PointOfInterestType = 3
	PointOfInterestType_WarpReceiver               PointOfInterestType = 4
	PointOfInterestType_GeneShuffler               PointOfInterestType = 5
	PointOfInterestType_MassiveHeatSink            PointOfInterestType = 6
	PointOfInterestType_SapTree                    PointOfInterestType = 7
	PointOfInterestType_GravitasPedestal           PointOfInterestType = 8
	PointOfInterestType_PropSurfaceSatellite1      PointOfInterestType = 9
	PointOfInterestType_PropSurfaceSatellite2      PointOfInterestType = 10
	PointOfInterestType_PropSurfaceSatellite3      PointOfInterestType = 11
	PointOfInterestType_TemporalTearOpener         PointOfInterestType = 12
	PointOfInterestType_CryoTank                   PointOfInterestType = 13
	PointOfInterestType_PropFacilityStatue         PointOfInterestType = 14
	PointOfInterestType_GeothermalVentEntity       PointOfInterestType = 15
	PointOfInterestType_GeothermalControllerEntity PointOfInterestType = 16
	PointOfInterestType_POICeresTechUnlock         PointOfInterestType = 17
)

// Enum value maps for PointOfInterestType.
var (
	PointOfInterestType_name = map[int32]string{
		0:  "Headquarters",
		1:  "WarpConduitSender",
		2:  "WarpConduitReceiver",
		3:  "WarpPortal",
		4:  "WarpReceiver",
		5:  "GeneShuffler",
		6:  "MassiveHeatSink",
		7:  "SapTree",
		8:  "GravitasPedestal",
		9:  "PropSurfaceSatellite1",
		10: "PropSurfaceSatellite2",
		11: "PropSurfaceSatellite3",
		12: "TemporalTearOpener",
		13: "CryoTank",
		14: "PropFacilityStatue",
		15: "GeothermalVentEntity",
		16: "GeothermalControllerEntity",
		17: "POICeresTechUnlock",
	}
	PointOfInterestType_value = map[string]int32{
		"Headquarters":               0,
		"WarpConduitSender":          1,
		"WarpConduitReceiver":        2,
		"WarpPortal":                 3,
		"WarpReceiver":               4,
		"GeneShuffler":               5,
		"MassiveHeatSink":            6,
		"SapTree":                    7,
		"GravitasPedestal":           8,
		"PropSurfaceSatellite1":      9,
		"PropSurfaceSatellite2":      10,
		"PropSurfaceSatellite3":      11,
		"TemporalTearOpener":         12,
		"CryoTank":                   13,
		"PropFacilityStatue":         14,
		"GeothermalVentEntity":       15,
		"GeothermalControllerEntity": 16,
		"POICeresTechUnlock":         17,
	}
)

func (x PointOfInterestType) Enum() *PointOfInterestType {
	p := new(PointOfInterestType)
	*p = x
	return p
}

func (x PointOfInterestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PointOfInterestType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_pb_seed_proto_enumTypes[0].Descriptor()
}

func (PointOfInterestType) Type() protoreflect.EnumType {
	return &file_data_pb_seed_proto_enumTypes[0]
}

func (x PointOfInterestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PointOfInterestType.Descriptor instead.
func (PointOfInterestType) EnumDescriptor() ([]byte, []int) {
	return file_data_pb_seed_proto_rawDescGZIP(), []int{0}
}

type Geyser struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X                     int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                     int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	EmitRate              int32                  `protobuf:"varint,4,opt,name=emitRate,proto3" json:"emitRate,omitempty"`
	AvgEmitRate           int32                  `protobuf:"varint,5,opt,name=avgEmitRate,proto3" json:"avgEmitRate,omitempty"`
	IdleTime              int32                  `protobuf:"varint,6,opt,name=idleTime,proto3" json:"idleTime,omitempty"`
	EruptionTime          int32                  `protobuf:"varint,7,opt,name=eruptionTime,proto3" json:"eruptionTime,omitempty"`
	DormancyCyclesRounded int32                  `protobuf:"varint,8,opt,name=dormancyCyclesRounded,proto3" json:"dormancyCyclesRounded,omitempty"`
	ActiveCyclesRounded   int32                  `protobuf:"varint,9,opt,name=activeCyclesRounded,proto3" json:"activeCyclesRounded,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Geyser) Reset() {
	*x = Geyser{}
	mi := &file_data_pb_seed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geyser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geyser) ProtoMessage() {}

func (x *Geyser) ProtoReflect() protoreflect.Message {
	mi := &file_data_pb_seed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geyser.ProtoReflect.Descriptor instead.
func (*Geyser) Descriptor() ([]byte, []int) {
	return file_data_pb_seed_proto_rawDescGZIP(), []int{0}
}

func (x *Geyser) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Geyser) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Geyser) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Geyser) GetEmitRate() int32 {
	if x != nil {
		return x.EmitRate
	}
	return 0
}

func (x *Geyser) GetAvgEmitRate() int32 {
	if x != nil {
		return x.AvgEmitRate
	}
	return 0
}

func (x *Geyser) GetIdleTime() int32 {
	if x != nil {
		return x.IdleTime
	}
	return 0
}

func (x *Geyser) GetEruptionTime() int32 {
	if x != nil {
		return x.EruptionTime
	}
	return 0
}

func (x *Geyser) GetDormancyCyclesRounded() int32 {
	if x != nil {
		return x.DormancyCyclesRounded
	}
	return 0
}

func (x *Geyser) GetActiveCyclesRounded() int32 {
	if x != nil {
		return x.ActiveCyclesRounded
	}
	return 0
}

type PointOfInterest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            PointOfInterestType    `protobuf:"varint,1,opt,name=id,proto3,enum=seedpb.PointOfInterestType" json:"id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointOfInterest) Reset() {
	*x = PointOfInterest{}
	mi := &file_data_pb_seed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointOfInterest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointOfInterest) ProtoMessage() {}

func (x *PointOfInterest) ProtoReflect() protoreflect.Message {
	mi := &file_data_pb_seed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointOfInterest.ProtoReflect.Descriptor instead.
func (*PointOfInterest) Descriptor() ([]byte, []int) {
	return file_data_pb_seed_proto_rawDescGZIP(), []int{1}
}

func (x *PointOfInterest) GetId() PointOfInterestType {
	if x != nil {
		return x.Id
	}
	return PointOfInterestType_Headquarters
}

func (x *PointOfInterest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PointOfInterest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Asteroid struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OffsetX            int32                  `protobuf:"varint,2,opt,name=offsetX,proto3" json:"offsetX,omitempty"`
	OffsetY            int32                  `protobuf:"varint,3,opt,name=offsetY,proto3" json:"offsetY,omitempty"`
	SizeX              int32                  `protobuf:"varint,4,opt,name=sizeX,proto3" json:"sizeX,omitempty"`
	SizeY              int32                  `protobuf:"varint,5,opt,name=sizeY,proto3" json:"sizeY,omitempty"`
	WorldTraitsBitmask int32                  `protobuf:"varint,6,opt,name=worldTraitsBitmask,proto3" json:"worldTraitsBitmask,omitempty"`
	BiomePaths         string                 `protobuf:"bytes,7,opt,name=biomePaths,proto3" json:"biomePaths,omitempty"`
	PointsOfInterest   []*PointOfInterest     `protobuf:"bytes,8,rep,name=pointsOfInterest,proto3" json:"pointsOfInterest,omitempty"`
	Geysers            []*Geyser              `protobuf:"bytes,9,rep,name=geysers,proto3" json:"geysers,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Asteroid) Reset() {
	*x = Asteroid{}
	mi := &file_data_pb_seed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asteroid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asteroid) ProtoMessage() {}

func (x *Asteroid) ProtoReflect() protoreflect.Message {
	mi := &file_data_pb_seed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asteroid.ProtoReflect.Descriptor instead.
func (*Asteroid) Descriptor() ([]byte, []int) {
	return file_data_pb_seed_proto_rawDescGZIP(), []int{2}
}

func (x *Asteroid) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Asteroid) GetOffsetX() int32 {
	if x != nil {
		return x.OffsetX
	}
	return 0
}

func (x *Asteroid) GetOffsetY() int32 {
	if x != nil {
		return x.OffsetY
	}
	return 0
}

func (x *Asteroid) GetSizeX() int32 {
	if x != nil {
		return x.SizeX
	}
	return 0
}

func (x *Asteroid) GetSizeY() int32 {
	if x != nil {
		return x.SizeY
	}
	return 0
}

func (x *Asteroid) GetWorldTraitsBitmask() int32 {
	if x != nil {
		return x.WorldTraitsBitmask
	}
	return 0
}

func (x *Asteroid) GetBiomePaths() string {
	if x != nil {
		return x.BiomePaths
	}
	return ""
}

func (x *Asteroid) GetPointsOfInterest() []*PointOfInterest {
	if x != nil {
		return x.PointsOfInterest
	}
	return nil
}

func (x *Asteroid) GetGeysers() []*Geyser {
	if x != nil {
		return x.Geysers
	}
	return nil
}

type Cluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asteroids     []*Asteroid            `protobuf:"bytes,7,rep,name=asteroids,proto3" json:"asteroids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_data_pb_seed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_data_pb_seed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_data_pb_seed_proto_rawDescGZIP(), []int{3}
}

func (x *Cluster) GetAsteroids() []*Asteroid {
	if x != nil {
		return x.Asteroids
	}
	return nil
}

var File_data_pb_seed_proto protoreflect.FileDescriptor

const file_data_pb_seed_proto_rawDesc = "" +
	"\n" +
	"\x12data/pb/seed.proto\x12\x06seedpb\"\x9a\x02\n" +
	"\x06Geyser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x1a\n" +
	"\bemitRate\x18\x04 \x01(\x05R\bemitRate\x12 \n" +
	"\vavgEmitRate\x18\x05 \x01(\x05R\vavgEmitRate\x12\x1a\n" +
	"\bidleTime\x18\x06 \x01(\x05R\bidleTime\x12\"\n" +
	"\feruptionTime\x18\a \x01(\x05R\feruptionTime\x124\n" +
	"\x15dormancyCyclesRounded\x18\b \x01(\x05R\x15dormancyCyclesRounded\x120\n" +
	"\x13activeCyclesRounded\x18\t \x01(\x05R\x13activeCyclesRounded\"Z\n" +
	"\x0fPointOfInterest\x12+\n" +
	"\x02id\x18\x01 \x01(\x0e2\x1b.seedpb.PointOfInterestTypeR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"\xb9\x02\n" +
	"\bAsteroid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aoffsetX\x18\x02 \x01(\x05R\aoffsetX\x12\x18\n" +
	"\aoffsetY\x18\x03 \x01(\x05R\aoffsetY\x12\x14\n" +
	"\x05sizeX\x18\x04 \x01(\x05R\x05sizeX\x12\x14\n" +
	"\x05sizeY\x18\x05 \x01(\x05R\x05sizeY\x12.\n" +
	"\x12worldTraitsBitmask\x18\x06 \x01(\x05R\x12worldTraitsBitmask\x12\x1e\n" +
	"\n" +
	"biomePaths\x18\a \x01(\tR\n" +
	"biomePaths\x12C\n" +
	"\x10pointsOfInterest\x18\b \x03(\v2\x17.seedpb.PointOfInterestR\x10pointsOfInterest\x12(\n" +
	"\ageysers\x18\t \x03(\v2\x0e.seedpb.GeyserR\ageysers\"9\n" +
	"\aCluster\x12.\n" +
	"\tasteroids\x18\a \x03(\v2\x10.seedpb.AsteroidR\tasteroids*\xa4\x03\n" +
	"\x13PointOfInterestType\x12\x10\n" +
	"\fHeadquarters\x10\x00\x12\x15\n" +
	"\x11WarpConduitSender\x10\x01\x12\x17\n" +
	"\x13WarpConduitReceiver\x10\x02\x12\x0e\n" +
	"\n" +
	"WarpPortal\x10\x03\x12\x10\n" +
	"\fWarpReceiver\x10\x04\x12\x10\n" +
	"\fGeneShuffler\x10\x05\x12\x13\n" +
	"\x0fMassiveHeatSink\x10\x06\x12\v\n" +
	"\aSapTree\x10\a\x12\x14\n" +
	"\x10GravitasPedestal\x10\b\x12\x19\n" +
	"\x15PropSurfaceSatellite1\x10\t\x12\x19\n" +
	"\x15PropSurfaceSatellite2\x10\n" +
	"\x12\x19\n" +
	"\x15PropSurfaceSatellite3\x10\v\x12\x16\n" +
	"\x12TemporalTearOpener\x10\f\x12\f\n" +
	"\bCryoTank\x10\r\x12\x16\n" +
	"\x12PropFacilityStatue\x10\x0e\x12\x18\n" +
	"\x14GeothermalVentEntity\x10\x0f\x12\x1e\n" +
	"\x1aGeothermalControllerEntity\x10\x10\x12\x16\n" +
	"\x12POICeresTechUnlock\x10\x11B\x19Z\x17oni-view/data/pb;seedpbb\x06proto3"

var (
	file_data_pb_seed_proto_rawDescOnce sync.Once
	file_data_pb_seed_proto_rawDescData []byte
)

func file_data_pb_seed_proto_rawDescGZIP() []byte {
	file_data_pb_seed_proto_rawDescOnce.Do(func() {
		file_data_pb_seed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_pb_seed_proto_rawDesc), len(file_data_pb_seed_proto_rawDesc)))
	})
	return file_data_pb_seed_proto_rawDescData
}

var file_data_pb_seed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_pb_seed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_data_pb_seed_proto_goTypes = []any{
	(PointOfInterestType)(0), // 0: seedpb.PointOfInterestType
	(*Geyser)(nil),           // 1: seedpb.Geyser
	(*PointOfInterest)(nil),  // 2: seedpb.PointOfInterest
	(*Asteroid)(nil),         // 3: seedpb.Asteroid
	(*Cluster)(nil),          // 4: seedpb.Cluster
}
var file_data_pb_seed_proto_depIdxs = []int32{
	0, // 0: seedpb.PointOfInterest.id:type_name -> seedpb.PointOfInterestType
	2, // 1: seedpb.Asteroid.pointsOfInterest:type_name -> seedpb.PointOfInterest
	1, // 2: seedpb.Asteroid.geysers:type_name -> seedpb.Geyser
	3, // 3: seedpb.Cluster.asteroids:type_name -> seedpb.Asteroid
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_data_pb_seed_proto_init() }
func file_data_pb_seed_proto_init() {
	if File_data_pb_seed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_pb_seed_proto_rawDesc), len(file_data_pb_seed_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_pb_seed_proto_goTypes,
		DependencyIndexes: file_data_pb_seed_proto_depIdxs,
		EnumInfos:         file_data_pb_seed_proto_enumTypes,
		MessageInfos:      file_data_pb_seed_proto_msgTypes,
	}.Build()
	File_data_pb_seed_proto = out.File
	file_data_pb_seed_proto_goTypes = nil
	file_data_pb_seed_proto_depIdxs = nil
}
