package main

import "fmt"

var asteroidNames = map[int32]string{
	0:  "Terra",
	1:  "Ceres (Base Game)",
	2:  "Blasted Ceres",
	3:  "Oceania",
	4:  "Rime",
	5:  "Verdante",
	6:  "Arboria",
	7:  "Volcanea",
	8:  "The Badlands",
	9:  "Aridio",
	10: "Oasisse",
	11: "Vanilla Terra",
	12: "Vanilla Radioactive Swamp",
	13: "Ceres (Classic)",
	14: "Stinko Swamp",
	15: "Vanilla Oceania",
	16: "Glowood Wasteland",
	17: "Vanilla Squelchy",
	18: "Vanilla Radioactive Forest",
	19: "Vanilla Rime",
	20: "Vanilla Verdante",
	21: "Vanilla Radioactive Terra",
	22: "Vanilla Arboria",
	23: "Vanilla Volcanea",
	24: "Vanilla Badlands",
	25: "Vanilla Aridio",
	26: "Vanilla Radioactive Terrabog",
	27: "Vanilla Oasisse",
	28: "Terrania",
	29: "Irradiated Forest",
	30: "Oily Swamp",
	31: "Regolith",
	32: "Ceres Minor",
	33: "Irradiated Swampy",
	34: "Rusty Oil",
	35: "Folia",
	36: "Quagmiris",
	37: "Irradiated Marsh",
	38: "The Desolands",
	39: "Metallic Swampy (Start)",
	40: "Frozen Forest (Warp)",
	41: "Flipped",
	42: "Radioactive Ocean",
	43: "The Desolands (Start)",
	44: "Radioactive Ocean (Warp)",
	45: "Metallic Swampy",
	46: "Frozen Forest",
	47: "Metallic Swampy (Warp)",
	48: "Frozen Forest (Start)",
	49: "Flipped (Start)",
	50: "Radioactive Ocean (Start)",
	51: "Flipped (Warp)",
	52: "Tundra",
	53: "Marshy",
	54: "Superconductive",
	55: "Moo",
	56: "Water",
	57: "Regolith Moonlet",
	58: "Mixing Ceres",
	59: "Ceres Classic Shattered",
	60: "Mini Shattered (Start)",
	61: "Mini Shattered (Warp)",
	62: "Mini Shattered (Geo)",
	63: "Prehistoric Base Game",
	64: "Prehistoric Classic",
	65: "Prehistoric Spaced Out",
	66: "Prehistoric Shattered Base Game",
	67: "Prehistoric Shattered Classic",
	68: "Mixing Prehistoric",
	69: "Warp Oily Sandy Swamp",
}

func asteroidNameFromID(id int32) string {
	if name, ok := asteroidNames[id]; ok {
		return name
	}
	return fmt.Sprintf("Asteroid %d", id)
}
