package main

import "fmt"

var asteroidNames = map[int32]string{
	0:  "Terra",
	1:  "Ceres",
	2:  "Blasted Ceres",
	3:  "Oceania",
	4:  "Rime",
	5:  "Verdante",
	6:  "Arboria",
	7:  "Volcanea",
	8:  "The Badlands",
	9:  "Aridio",
	10: "Oasisse",
	11: "Terra",
	12: "Radioactive Swamp",
	13: "Ceres",
	14: "Stinko Swamp",
	15: "Oceania",
	16: "Glowood Wasteland",
	17: "Squelchy",
	18: "Radioactive Forest",
	19: "Rime",
	20: "Verdante",
	21: "Radioactive Terra",
	22: "Arboria",
	23: "Volcanea",
	24: "The Badlands",
	25: "Aridio",
	26: "Radioactive Terrabog",
	27: "Oasisse",
	28: "Terrania",
	29: "Irradiated Forest",
	30: "Oily Swamp",
	31: "Regolith",
	32: "Ceres Minor",
	33: "Irradiated Swampy",
	34: "Rusty Oil",
	35: "Folia",
	36: "Quagmiris",
	37: "Irradiated Marsh",
	38: "The Desolands",
	39: "Metallic Swampy",
	40: "Frozen Forest",
	41: "Flipped",
	42: "Radioactive Ocean",
	43: "The Desolands",
	44: "Radioactive Ocean",
	45: "Metallic Swampy",
	46: "Frozen Forest",
	47: "Metallic Swampy",
	48: "Frozen Forest",
	49: "Flipped",
	50: "Radioactive Ocean",
	51: "Flipped",
	52: "Tundra",
	53: "Marshy",
	54: "Superconductive",
	55: "Moo",
	56: "Water",
	57: "Regolith",
	58: "MixingCeresAsteroid",
	59: "CeresClassicShatteredAsteroid",
	60: "MiniShatteredStartAsteroid",
	61: "MiniShatteredWarpAsteroid",
	62: "MiniShatteredGeoAsteroid",
	63: "PrehistoricBaseGameAsteroid",
	64: "PrehistoricClassicAsteroid",
	65: "PrehistoricSpacedOutAsteroid",
	66: "PrehistoricShatteredBaseGameAsteroid",
	67: "PrehistoricShatteredClassicAsteroid",
	68: "MixingPrehistoricAsteroid",
	69: "WarpOilySandySwamp",
}

func asteroidNameFromID(id int32) string {
	if name, ok := asteroidNames[id]; ok {
		return name
	}
	return fmt.Sprintf("Asteroid %d", id)
}
