package main

import "fmt"

var asteroidNames = map[int32]string{
	0:  "Terra",
	1:  "Ceres (Base Game)",
	2:  "Blasted Ceres",
	3:  "Oceania",
	4:  "Rime",
	5:  "Verdante",
	6:  "Arboria",
	7:  "Volcanea",
	8:  "The Badlands",
	9:  "Aridio",
	10: "Oasisse",
	11: "Vanilla Terra",
	12: "Vanilla Radioactive Swamp",
	13: "Ceres (Classic)",
	14: "Stinko Swamp",
	15: "Vanilla Oceania",
	16: "Glowood Wasteland",
	17: "Vanilla Squelchy",
	18: "Vanilla Radioactive Forest",
	19: "Vanilla Rime",
	20: "Vanilla Verdante",
	21: "Vanilla Radioactive Terra",
	22: "Vanilla Arboria",
	23: "Vanilla Volcanea",
	24: "Vanilla Badlands",
	25: "Vanilla Aridio",
	26: "Vanilla Radioactive Terrabog",
	27: "Vanilla Oasisse",
	28: "Terrania",
	29: "Irradiated Forest",
	30: "Oily Swamp",
	31: "Regolith",
	32: "Ceres Minor",
	33: "Irradiated Swampy",
	34: "Rusty Oil",
	35: "Folia",
	36: "Quagmiris",
	37: "Irradiated Marsh",
	38: "The Desolands",
	39: "Metallic Swampy (Start)",
	40: "Frozen Forest (Warp)",
	41: "Flipped",
	42: "Radioactive Ocean",
	43: "The Desolands (Start)",
	44: "Radioactive Ocean (Warp)",
	45: "Metallic Swampy",
	46: "Frozen Forest",
	47: "Metallic Swampy (Warp)",
	48: "Frozen Forest (Start)",
	49: "Flipped (Start)",
	50: "Radioactive Ocean (Start)",
	51: "Flipped (Warp)",
	52: "Tundra",
	53: "Marshy",
	54: "Superconductive",
	55: "Moo",
	56: "Water",
	57: "Regolith Moonlet",
	58: "Mixing Ceres",
	59: "Ceres Classic Shattered",
	60: "Mini Shattered (Start)",
	61: "Mini Shattered (Warp)",
	62: "Mini Shattered (Geo)",
	63: "Prehistoric Base Game",
	64: "Prehistoric Classic",
	65: "Prehistoric Spaced Out",
	66: "Prehistoric Shattered Base Game",
	67: "Prehistoric Shattered Classic",
	68: "Mixing Prehistoric",
	69: "Warp Oily Sandy Swamp",
}

var asteroidAliases = map[string]string{
	"SandstoneDefault":                   asteroidNames[0],
	"CeresBaseGameAsteroid":              asteroidNames[1],
	"CeresBaseGameShatteredAsteroid":     asteroidNames[2],
	"Oceania":                            asteroidNames[3],
	"SandstoneFrozen":                    asteroidNames[4],
	"ForestLush":                         asteroidNames[5],
	"ForestDefault":                      asteroidNames[6],
	"Volcanic":                           asteroidNames[7],
	"Badlands":                           asteroidNames[8],
	"ForestHot":                          asteroidNames[9],
	"Oasis":                              asteroidNames[10],
	"VanillaSandstoneDefault":            asteroidNames[11],
	"MediumRadioactiveVanillaWarpPlanet": asteroidNames[12],
	"CeresClassicAsteroid":               asteroidNames[13],
	"MediumSwampy":                       asteroidNames[14],
	"VanillaOceania":                     asteroidNames[15],
	"MediumForestyWasteland":             asteroidNames[16],
	"VanillaSwampDefault":                asteroidNames[17],
	"MediumForestyRadioactiveVanillaWarpPlanet": asteroidNames[18],
	"VanillaSandstoneFrozen":                    asteroidNames[19],
	"VanillaForestDefault":                      asteroidNames[20],
	"MediumSandyRadioactiveVanillaWarpPlanet":   asteroidNames[21],
	"VanillaArboria":                            asteroidNames[22],
	"VanillaVolcanic":                           asteroidNames[23],
	"VanillaBadlands":                           asteroidNames[24],
	"VanillaAridio":                             asteroidNames[25],
	"MediumSandySwamp":                          asteroidNames[26],
	"VanillaOasis":                              asteroidNames[27],
	"TerraMoonlet":                              asteroidNames[28],
	"IdealLandingSite":                          asteroidNames[29],
	"WarpOilySwamp":                             asteroidNames[30],
	"RegolithMoonlet":                           asteroidNames[31],
	"CeresSpacedOutAsteroid":                    asteroidNames[32],
	"SwampyLandingSite":                         asteroidNames[33],
	"OilRichWarpTarget":                         asteroidNames[34],
	"ForestMoonlet":                             asteroidNames[35],
	"SwampMoonlet":                              asteroidNames[36],
	"MetalHeavyLandingSite":                     asteroidNames[37],
	"MiniBadlands":                              asteroidNames[38],
	"MiniMetallicSwampyStart":                   asteroidNames[39],
	"MiniForestFrozenWarp":                      asteroidNames[40],
	"MiniFlipped":                               asteroidNames[41],
	"MiniRadioactiveOcean":                      asteroidNames[42],
	"MiniBadlandsStart":                         asteroidNames[43],
	"MiniRadioactiveOceanWarp":                  asteroidNames[44],
	"MiniMetallicSwampy":                        asteroidNames[45],
	"MiniForestFrozen":                          asteroidNames[46],
	"MiniBadlandsWarp":                          asteroidNames[47],
	"MiniForestFrozenStart":                     asteroidNames[48],
	"MiniFlippedStart":                          asteroidNames[49],
	"MiniRadioactiveOceanStart":                 asteroidNames[50],
	"MiniFlippedWarp":                           asteroidNames[51],
	"TundraMoonlet":                             asteroidNames[52],
	"MarshyMoonlet":                             asteroidNames[53],
	"NiobiumMoonlet":                            asteroidNames[54],
	"MooMoonlet":                                asteroidNames[55],
	"WaterMoonlet":                              asteroidNames[56],
	"MiniRegolithMoonlet":                       asteroidNames[57],
	"MixingCeresAsteroid":                       asteroidNames[58],
	"CeresClassicShatteredAsteroid":             asteroidNames[59],
	"MiniShatteredStartAsteroid":                asteroidNames[60],
	"MiniShatteredWarpAsteroid":                 asteroidNames[61],
	"MiniShatteredGeoAsteroid":                  asteroidNames[62],
	"PrehistoricBaseGameAsteroid":               asteroidNames[63],
	"PrehistoricClassicAsteroid":                asteroidNames[64],
	"PrehistoricSpacedOutAsteroid":              asteroidNames[65],
	"PrehistoricShatteredBaseGameAsteroid":      asteroidNames[66],
	"PrehistoricShatteredClassicAsteroid":       asteroidNames[67],
	"MixingPrehistoricAsteroid":                 asteroidNames[68],
	"WarpOilySandySwamp":                        asteroidNames[69],
}

func asteroidNameFromID(id int32) string {
	if name, ok := asteroidNames[id]; ok {
		return name
	}
	return fmt.Sprintf("Asteroid %d", id)
}

func normalizeAsteroidID(id string) string {
	if name, ok := asteroidAliases[id]; ok {
		return name
	}
	return id
}
