name: build-and-release

on:
  push:
    tags:
      - 'v*'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xorg-dev libgl1-mesa-dev mingw-w64
      - name: Run tests
        run: go test -tags test ./...
      - name: Build binaries
        run: ./scripts/build_all.sh
      - uses: actions/upload-artifact@v4
        with:
          name: oni-view-builds
          path: dist

  release:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: oni-view-builds
          path: dist
      - uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/**

