name: build-and-release

on:
  push:
    tags:
      - 'v*'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y xvfb webp
      - name: Download assets
        run: ./scripts/download_assets.sh
      - name: Run tests
        run: xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' go test ./...
      - name: Build binaries
        run: ./scripts/build_all.sh
      - name: Copy assets
        run: |
          cp -r assets dist/
          cp -r icons dist/
      - uses: actions/upload-artifact@v4
        with:
          name: oni-view-builds
          path: dist

  release:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: oni-view-builds
          path: dist
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**

